const errorConstants=
{
  
	PROVIDER_SCHEDULE_INVALID : "PS-I",
    PROVIDER_SCHEDULE_INVALID_USER : "PS-IUSR",
    PROVIDER_SCHEDULE_PROVIDER_NOT_FOUND : "PS-PNF",
    PROVIDER_SCHEDULE_EXISTING_ITEM : "PS-EI",
    PROVIDER_SCHEDULE_ITEM_NOT_FOUND : "PS-INF",
    USER_NOT_AUTHORIZE: "USR-NA"
   
    
	
};
module.exports =errorConstants;